# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be0bb59599949c335ecd2bfb918b116c10086e87ecfe970e0ce7d58bbb05f02bca7aa808c494a6c9de0a2a3639c63cb8005af56fedf3dc8ef3a06ea203452cb0

test:
  secret_key_base: 2a42931fa683067764d95bae7ca140ff6618fb25f949248f150a9e9134518dc09e06ff8ed8ab90bdb252f1ebc21646482eb4b5ee73daca18cc43ad080739c72b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
